/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Donation = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'donorName' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'message' : IDL.Opt(IDL.Text),
  'amount' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const EmergencyRequest = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'phone' : IDL.Text,
  'location' : IDL.Text,
  'problem' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'caption' : IDL.Opt(IDL.Text),
  'blobId' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
  'photoBlobId' : IDL.Opt(IDL.Text),
});
export const Volunteer = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'eduProofBlobId' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'idProofBlobId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
      [IDL.Text],
      [],
    ),
  'addTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getDonors' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getEmergencyRequests' : IDL.Func([], [IDL.Vec(EmergencyRequest)], ['query']),
  'getGallery' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getSiteSettings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markContactRead' : IDL.Func([IDL.Text], [], []),
  'markEmergencyRead' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitDonation' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text), IDL.Bool],
      [IDL.Text],
      [],
    ),
  'submitEmergency' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitVolunteer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'updateSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateVolunteerStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Donation = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'donorName' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'message' : IDL.Opt(IDL.Text),
    'amount' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const EmergencyRequest = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'phone' : IDL.Text,
    'location' : IDL.Text,
    'problem' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'caption' : IDL.Opt(IDL.Text),
    'blobId' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
    'photoBlobId' : IDL.Opt(IDL.Text),
  });
  const Volunteer = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'eduProofBlobId' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'idProofBlobId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
        [IDL.Text],
        [],
      ),
    'addTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getDonors' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getEmergencyRequests' : IDL.Func(
        [],
        [IDL.Vec(EmergencyRequest)],
        ['query'],
      ),
    'getGallery' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getSiteSettings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markContactRead' : IDL.Func([IDL.Text], [], []),
    'markEmergencyRead' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitDonation' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text), IDL.Bool],
        [IDL.Text],
        [],
      ),
    'submitEmergency' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitVolunteer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'updateSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'updateVolunteerStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };