/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Donation {
  'id' : string,
  'createdAt' : bigint,
  'donorName' : string,
  'isAnonymous' : boolean,
  'message' : [] | [string],
  'amount' : [] | [bigint],
}
export interface EmergencyRequest {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'phone' : string,
  'location' : string,
  'problem' : string,
}
export interface GalleryItem {
  'id' : string,
  'order' : bigint,
  'caption' : [] | [string],
  'blobId' : string,
}
export interface TeamMember {
  'id' : string,
  'order' : bigint,
  'name' : string,
  'role' : string,
  'isActive' : boolean,
  'photoBlobId' : [] | [string],
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Volunteer {
  'id' : string,
  'status' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'address' : string,
  'eduProofBlobId' : [] | [string],
  'phone' : string,
  'idProofBlobId' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryItem' : ActorMethod<[string, [] | [string], bigint], string>,
  'addTeamMember' : ActorMethod<
    [string, string, [] | [string], bigint],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGalleryItem' : ActorMethod<[string], undefined>,
  'deleteTeamMember' : ActorMethod<[string], undefined>,
  'getAllDonations' : ActorMethod<[], Array<Donation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getDonors' : ActorMethod<[], Array<Donation>>,
  'getEmergencyRequests' : ActorMethod<[], Array<EmergencyRequest>>,
  'getGallery' : ActorMethod<[], Array<GalleryItem>>,
  'getSiteSettings' : ActorMethod<[], Array<[string, string]>>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markContactRead' : ActorMethod<[string], undefined>,
  'markEmergencyRead' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContact' : ActorMethod<[string, string, string, string], string>,
  'submitDonation' : ActorMethod<
    [string, [] | [bigint], [] | [string], boolean],
    string
  >,
  'submitEmergency' : ActorMethod<[string, string, string, string], string>,
  'submitVolunteer' : ActorMethod<
    [string, string, string, string, string, [] | [string]],
    string
  >,
  'updateSetting' : ActorMethod<[string, string], undefined>,
  'updateTeamMember' : ActorMethod<
    [string, string, string, [] | [string], bigint, boolean],
    undefined
  >,
  'updateVolunteerStatus' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];